NUM_RIGHE EQU 4
NUM_COLONNE EQU 6
.MODEL small
.STACK
.DATA
TAB DW  154,123,109,86,4,?
    DW  412,-23,-231,9,50,?
    DW  123,-24,12,55,-45,?
    DW  ?,?,?,?,?,?
.CODE
.STARTUP
XOR AX,AX
XOR BX,BX
XOR SI,SI

ciclo1:
ADD AX,TAB[BX][SI]
ADD SI,2
CMP SI,2*(NUM_COLONNE-1)      ;??BUG di EMU: non riconosce (NUM_COLONNE-1)*2
JNZ ciclo1  
;MOV TAB[BX][(NUM_COLONNE-1)*2],AX  ma magari usiamo SI
MOV TAB[BX][SI],AX
XOR AX,AX
XOR SI,SI
ADD BX,NUM_COLONNE*2
CMP BX,NUM_COLONNE*NUM_RIGHE*2
JNZ ciclo1

XOR AX,AX
XOR BX,BX
XOR SI,SI
ciclo2:
ADD AX,TAB[BX][SI]
ADD BX,NUM_COLONNE*2
CMP BX,2*NUM_COLONNE*(NUM_RIGHE-1)      
JNZ ciclo2  
MOV TAB[BX][SI],AX
XOR AX,AX
XOR BX,BX
ADD SI,2
CMP SI,NUM_COLONNE*2
JNZ ciclo2


.EXIT
END